DELETE FROM gameobject_template WHERE `type`=2 AND `CustomData1`=3643;

SET @Entry := 190011;

DELETE FROM `creature_template` WHERE `entry` = @Entry;
INSERT INTO `creature_template` (`entry`, `DisplayId1`, `DisplayIdProbability1`, `name`, `subname`, `GossipMenuId`, `minlevel`, `maxlevel`, `faction`, `NpcFlags`, `scale`, `rank`, `DamageSchool`, `MeleeBaseAttackTime`, `RangedBaseAttackTime`, `unitClass`, `unitFlags`, `CreatureType`, `CreatureTypeFlags`, `lootid`, `PickpocketLootId`, `SkinningLootId`, `AIName`, `MovementType`, `RacialLeader`, `RegenerateStats`, `MechanicImmuneMask`, `ExtraFlags`) VALUES
(@Entry, 1403, 100, "\"Masochist\" Pete", "Challenge Advisor", 0, 60, 60, 35, 1, 1, 0, 0, 2000, 0, 1, 0, 7, 138936390, 0, 0, 0, '', 0, 0, 1, 0, 0);

DELETE FROM `locales_creature` WHERE `entry` = @Entry;
INSERT INTO `locales_creature` (`entry`, `name_loc6`, `subname_loc6`) VALUES (@Entry, "Pedro \"El Masoca\"", 'Asesor de Desafios');

DELETE FROM `creature` WHERE `id` = @Entry;
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 0, 1, -8999.00000000000000000000, 851.19100000000000000000, 29.62100000000000000000, 3.88538000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 1, 1, 1467.40000000000000000000, -4226.33000000000000000000, 58.99390000000000000000, 1.19063000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 0, 1, -8903.58000000000000000000, -108.40100000000000000000, 81.84860000000000000000, 4.08677000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 0, 1, -6213.26000000000000000000, 330.66400000000000000000, 383.71900000000000000000, 2.89842000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 1, 1, 10327.10000000000000000000, 822.52100000000000000000, 1326.43000000000000000000, 2.53681000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 1, 1, -638.98100000000000000000, -4227.08000000000000000000, 38.13420000000000000000, 5.47014000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 0, 1, 1859.94000000000000000000, 1560.67000000000000000000, 99.07910000000000000000, 1.57723000000000000000, 25, 25, 0, 0);
INSERT INTO `creature` (`id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `MovementType`) VALUES (@Entry, 1, 1, -2882.11000000000000000000, -277.04500000000000000000, 53.91540000000000000000, 2.37644000000000000000, 25, 25, 0, 0);

SET @TEXT_ID := 50900;
DELETE FROM `npc_text` WHERE `ID` BETWEEN @TEXT_ID AND @TEXT_ID+16;
INSERT INTO `npc_text` (`ID`, `text0_0`) VALUES
(@TEXT_ID,    "Ahoy, $N. If you are looking for a challenge you have come to the right place. Tell me, what challenge are you interested in?"),
(@TEXT_ID+1,  "Appologies $N. I can't provide you with any challenges at the moment."),
(@TEXT_ID+2,  "Oh, the hardcore challenge you say? I thought you'd never ask... If you accept this challenge, it means you will only have one life and if you die, that's it, no more retries. Are you up for it?"),
(@TEXT_ID+3,  "Hmm, the drop loot challenge? This challenge will make you drop some of your belongings every time you die, including gear and gold. What do you say?"),
(@TEXT_ID+4,  "Ah, the classic lose experience challenge. This challenge will make you lose some experience every time you die, and if you die enough you can even lose levels. Interested?"),
(@TEXT_ID+5,  "The self found challenge... I see you are a lone wolf like me. Just to clarify, this means you won't be able to use any help from any other adventurer, unless they are in the same challenge as you. Ready for it?"),
(@TEXT_ID+6,  "Hold your horses cowboy! It seems like your journey has already taken its course. To start this challenge you must speak with me with a fresh start, if you know what I mean..."),
(@TEXT_ID+7,  "I know you are excited about this challenge, but you seem like you already accepted it. What do you want, to double accept it?"),
(@TEXT_ID+8,  "Hahaha! That's what I'm talking about! Good luck! You will need it..."),
(@TEXT_ID+9,  "Oh, so you don’t want people attacking you during the challenge? That’s cute... But hey, who am I to judge..."),
(@TEXT_ID+10, "All right then... Consider it done. Careful not to break a nail out there."),
(@TEXT_ID+11, "Are you sure? You won't be able to retake the challenge if you drop it now."),
(@TEXT_ID+12, "Oh! That is such a relieve! I was wondering how long were you going to keep joking around..."),
(@TEXT_ID+13, "All done! Enemies will be able to attack you now."),
(@TEXT_ID+14, "All done! You are no longer doing the challenge."),
(@TEXT_ID+15, "Which XP rate would you like to have?"),
(@TEXT_ID+16, "All done! You xp rate has been changed.");

DELETE FROM `locales_npc_text` WHERE `entry` BETWEEN @TEXT_ID AND @TEXT_ID+14;
INSERT INTO `locales_npc_text` (`entry`, `text0_0_loc6`) VALUES
(@TEXT_ID,    "¡Hola, $N! Si estas buscando un reto, estás en el lugar indicado. Dime, ¿qué reto te interesa?"),
(@TEXT_ID+1,  "Mis disculpas $N. No tengo ningun desafío disponible en estos momentos."),
(@TEXT_ID+2,  "¿El desafío hardcore dices? Creí que nunca me lo preguntarías... Si aceptas este desafío, significa que solo tendrás una vida y, si mueres, se acabó, no habrá más reintentos. ¿Te animas?"),
(@TEXT_ID+3,  "Mmm, ¿el desafío de perder posesiones? Este desafío te hará soltar algunas de tus pertenencias cada vez que mueras, incluyendo equipo y oro. ¿Qué me dices?"),
(@TEXT_ID+4,  "Ah, el clásico desafío de perder experiencia. Este desafío te hará perder experiencia cada vez que mueras, y si mueres lo suficiente, incluso puedes perder niveles. ¿Te interesa?"),
(@TEXT_ID+5,  "El desafío del lobo solitario... Supongo que eres de los que prefiere ir solo que mal acompañado, eh?. Solo para aclarar, esto significa que no podrás usar la ayuda de ningún otro aventurero, a menos que esté en el mismo desafío que tú. ¿Estas listo?"),
(@TEXT_ID+6,  "¡Calma, vaquero! Parece que tu viaje ya ha tomado su curso. Para empezar este reto, debes hablar conmigo desde el principio, si sabes a que me refiero..."),
(@TEXT_ID+7,  "Sé que estás entusiasmado con este reto, pero parece que ya lo has aceptado. ¿Qué quieres, aceptarlo dos veces?"),
(@TEXT_ID+8,  "¡Jajaja! ¡Eso es lo que queria escuchar! ¡Mucha suerte! La necesitarás..."),
(@TEXT_ID+9,  "¿Ah, entonces no quieres que otras personas te ataquen durante el desafío? Qué monada... Pero bueno, ¿quién soy yo para juzgar?"),
(@TEXT_ID+10, "De acuerdo, ya estas listo. Ve con cuidado por ahi, no vaya a ser que te rompas una uña."),
(@TEXT_ID+11, "¿Estas seguro? No podras retomar el desafío si lo terminas ahora."),
(@TEXT_ID+12, "Ah! Que alivio! Ya estaba pensando que de verdad ibas en serio..."),
(@TEXT_ID+13, "¡Listo! Los enemigos podrán combatir contigo ahora."),
(@TEXT_ID+14, "¡Listo! Ya no estas realizando el desafío."),
(@TEXT_ID+15, "¿Que ratio de XP te gustaria tener?"),
(@TEXT_ID+16, "¡Listo! He cambiado tu ratio de XP");

SET @STRING_ENTRY := 12200;
DELETE FROM `mangos_string` WHERE `entry` BETWEEN @STRING_ENTRY AND @STRING_ENTRY+14;
INSERT INTO `mangos_string` (`entry`, `content_default`, `content_loc6`) VALUES 
(@STRING_ENTRY,    "I'm interested in the hardcore challenge", "Estoy interesado en el desafío hardcore"),
(@STRING_ENTRY+1,  "I would like to stop doing the hardcore challenge", "Me gustaria terminar el desafío hardcore"),
(@STRING_ENTRY+2,  "I'm interested in the drop loot challenge", 'Estoy interesado en el desafío de perder posesiones'),
(@STRING_ENTRY+3,  "I would like to stop doing the drop loot challenge", 'Me gustaria terminar el desafío de perder posesiones'),
(@STRING_ENTRY+4,  "I'm interested in the lose experience challenge", 'Estoy interesado en el desafío de perder experiencia'),
(@STRING_ENTRY+5,  "I would like to stop doing the lose experience challenge", 'Me gustaria terminar el desafío de perder experiencia'),
(@STRING_ENTRY+6,  "I'm interested in the self found challenge", 'Estoy interesado en el desafío del lobo solitario'),
(@STRING_ENTRY+7,  "I would like to stop doing the self found challenge", 'Me gustaria terminar el desafío del lobo solitario'),
(@STRING_ENTRY+8,  "I would like to change my xp rate", 'Me gustaria cambiar el ratio de XP'),
(@STRING_ENTRY+9,  "I accept the challenge!", '¡Acepto el desafío!'),
(@STRING_ENTRY+10,  "Maybe later...", 'Quizas mas tarde...'),
(@STRING_ENTRY+11, "I would like to disable pvp fights", 'Me gustaria desactivar el combate pvp'),
(@STRING_ENTRY+12, "I would like to enable pvp fights", 'Me gustaria activat el combate pvp'),
(@STRING_ENTRY+13, "Yes, please!", '¡Si, por favor!'),
(@STRING_ENTRY+14, "Maybe not...", 'Quizas no...');

SET @START_SPELL_ID := 33500;
SET @END_SPELL_ID := @START_SPELL_ID+1;
DELETE FROM `spell_template` WHERE `Id` BETWEEN  @START_SPELL_ID AND @END_SPELL_ID;
INSERT INTO `spell_template`              (`Id`,              `School`, `Category`, `CastUI`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `Stances`,   `StancesNot`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `CasterAuraState`, `TargetAuraState`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaxLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerlevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectBaseDice1`, `EffectBaseDice2`, `EffectBaseDice3`, `EffectDicePerLevel1`, `EffectDicePerLevel2`, `EffectDicePerLevel3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `SpellVisual`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName`,             `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `Rank1`,  `Rank2`, `Rank3`, `Rank4`, `Rank5`, `Rank6`, `Rank7`, `Rank8`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaxTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `MaxAffectedTargets`, `DmgClass`, `PreventionType`, `StanceBarOrder`, `DmgMultiplier1`, `DmgMultiplier2`, `DmgMultiplier3`, `MinFactionId`, `MinReputation`, `RequiredAuraVision`, `EffectBonusCoefficient1`, `EffectBonusCoefficient2`, `EffectBonusCoefficient3`, `EffectBonusCoefficientFromAP1`, `EffectBonusCoefficientFromAP2`, `EffectBonusCoefficientFromAP3`, `IsServerSide`, `AttributesServerside`) VALUES 
/* Hardcore Challenge          (33500) */ (@START_SPELL_ID,    0,        0,          0,        0,        0,          2147483648,   0,              0,               1048576,         0,               0,           0,            0,         0,                    0,                    0,                 0,                 0,                  0,              0,                      0,                0,                    0,                       0,           101,          0,             0,          1,           1,            21,              0,           0,          0,                  0,               0,                       13,           0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               6,         0,         0,         1,                 0,                 0,                 1,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 1,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    4,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  0,                     0,                     0,                     0,                            0,                            0,                            222,           61,            0,              0,              'Hardcore Challenge',     '',           '',           '',            '',          '',           '',           '',           '',       '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                0,                 0,                  0,                    0,          0,                -1,               1,                1,                1,                0,              0,               0,                    1,                         0.2,                       0,                         0,                               0,                               0,                               0,              0),
/* Self Found Challenge        (33501) */ (@START_SPELL_ID+1,  0,        0,          0,        0,        0,          2147483648,   0,              0,               1048576,         0,               0,           0,            0,         0,                    0,                    0,                 0,                 0,                  0,              0,                      0,                0,                    0,                       0,           101,          0,             0,          1,           1,            21,              0,           0,          0,                  0,               0,                       13,           0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               6,         0,         0,         1,                 0,                 0,                 1,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 1,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    4,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  0,                     0,                     0,                     0,                            0,                            0,                            222,           1573,          0,              0,              'Self Found Challenge',   '',           '',           '',            '',          '',           '',           '',           '',       '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                0,                 0,                  0,                    0,          0,                -1,               1,                1,                1,                0,              0,               0,                    1,                         0.2,                       0,                         0,                               0,                               0,                               0,              0);